// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return UnitTest.run(function() {
      window.Q = uQuery;
      console.log("Begin test for real JQuery! -- each function");
      $('div').each(function(index) {
        return console.log(index);
      });
      console.log("Begin test for Clark's bullshit UQuery -- each function");
      Q('div').each(function(index) {
        return console.log(index);
      });
      console.log("Begin test for real JQuery! -- Output of JQuery");
      console.log($('#mocha p'));
      console.log("Begin test for Clark's bullshit UQuery -- Output of UQuery");
      return console.log(Q('#mocha p'));
    });
  });

}).call(this);
