// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return UnitTest.run(function() {
      var actual, expected;
      window.Q = uQuery;
      actual = function() {
        return $('div').each(function(index) {
          return index;
        });
      };
      expected = function() {
        return Q('div').each(function(index) {
          return index;
        });
      };
      this.verify(actual, expected, "Verify basic output : Q('div')");
      actual = function() {
        return $('#mocha p');
      };
      expected = function() {
        return Q('#mocha p');
      };
      this.verify(actual, expected, "Verify basic output : Q('#mocha p')");
      actual = function() {
        return $("bacon").remove();
      };
      expected = function() {
        return Q("bacon").remove();
      };
      this.verify(actual, expected, "Verify basic remove : bacon");
      actual = function() {
        $('div.hello').remove();
        return $('div.hello').length;
      };
      $('div.goodbye').addClass('hello');
      expected = function() {
        Q('div.hello').remove();
        return Q('div.hello').length;
      };
      this.verify(actual, expected, "Verify basic get remove : div.hello length");
      actual = function() {
        return $('li').filter(':even');
      };
      expected = function() {
        return Q('li').filter(':even');
      };
      this.verify(actual, expected, "Verify basic get : filter :even");
      actual = function() {
        $('li').filter(function(index) {});
        return $("strong", this).length === 1;
      };
      expected = function() {
        Q('li').filter(function(index) {});
        return Q("strong", this).length === 1;
      };
      this.verify(actual, expected, "Verify basic get : filter li index");
      actual = function() {
        return $('li').get(0);
      };
      expected = function() {
        return Q('li').get(0);
      };
      this.verify(actual, expected, "Verify basic get : li(0)");
      actual = function() {
        return $('li').get(1);
      };
      expected = function() {
        return Q('li').get(1);
      };
      this.verify(actual, expected, "Verify basic get : li(1)");
      actual = function() {
        return $('div').eq(1);
      };
      expected = function() {
        return Q('div').eq(1);
      };
      return this.verify(actual, expected, "Verify basic get : div");
    });
  });

}).call(this);
