// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return UnitTest.run(function() {
      window.Q = uQuery;
      this.assertEvalEqual(4, "Q('div').length");
      this.assertEvalEqual(0, "Q('dl').length");
      this.assertEvalEqual(3, "Q('.desert').length");
      this.assertEvalEqual(1, "Q('#pie').length");
      this.assertEvalEqual(3, "Q('div.desert').length");
      this.assertEvalEqual('icing', "Q('div.desert .desert').get(0).id");
      this.assertEvalEqual('desert', "Q('div#pie').get(0).className");
      this.assertEvalEqual(0, "Q('#lettuce').length");
      this.assertEvalEqual(0, "Q('.vegetable').length");
      Q('.vegetable').remove();
      Q('#pie').remove();
      this.assertEvalEqual(2, "Q('.desert').length");
      this.assertEvalEqual(0, "Q('#pie').length");
      this.assertEvalEqual(2, "Q('div.desert').length");
      return this.assertEvalEqual(0, "Q('div#pie').length");
    });
  });

}).call(this);
