// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return UnitTest.run(function() {
      window.Q = uQuery;
      return this.assertEvalEqual(1, "Q('div.desert .desert').length");
    });
  });

}).call(this);
